### ISSUE TITLE
QN inconsistency in the elections

### ISSUE THREAD

**Issue by thesan** [Joystream/joystream#3573]
There has been some inconsistency on the elections data returned by the QN on the olympia testnet:

### I. Rogue vote detected by user that they did not do (Joystream/pioneer#2753)
5HT8Mty5U5hFKVwv24uFswX2e41vurU3F5rkLMoETR8XmjFy

```gql
query Wrong_Votes_Bug {
  voteCastEvents(where: {inBlock_lte: 43200, AND: {castVote: {castBy_eq: "5HT8Mty5U5hFKVwv24uFswX2e41vurU3F5rkLMoETR8XmjFy"}}}) {
    castVote {
      stake
      voteFor {
        memberId
        stake
        status
      }
      castBy
    }
    inBlock
  }
}
```

![Screenshot 2022-04-01 at 11.28.15.png](https://images.zenhubusercontent.com/6197874e1913711bf1f6ad31/6d488b07-1934-4997-ae89-60935ad6bf70)

### II. The `councilElections` field is empty on the elected council
the currently elected council has an empty councilElections field and on the previous council nextCouncilElections.isFinished is false.

```gql
query {
  electedCouncils {
    isResigned
    electedAtTime
    councilElections { isFinished }
    nextCouncilElections { isFinished }
  }
}
```

![Screenshot from 2022-04-07 12-37-19](https://user-images.githubusercontent.com/6571453/162181013-0ef2750b-d012-4159-9284-83c3bf729a98.png)

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201709380879215/1202093277058287) by [Unito](https://www.unito.io)

**Comment by thesan** [comment]
The problem `II` is back on [`query.joystream.org`](https://query.joystream.org/graphql), now the currently elected council `000004` has an empty `councilElections` field and the latest election round available (which shows as unfinished) is the one which elected the previous council `000003`.

![Screenshot from 2022-04-19 12-54-26](https://user-images.githubusercontent.com/6571453/163988894-084b87ce-a165-4df7-876b-dfac47c9590e.png)

**Comment by ondratra** [comment]
The issue I. is solved. Issue II. should also be solved, but it's not easy to verify that as it sometimes looked ok even in the previous version. Please check it @thesan .

**Comment by thesan** [comment]
@ondratra it looks like issue II is not solved:
ATM (the council is on the "Normal period")
```gql
query {
  electionRounds (orderBy: [createdAt_DESC] limit: 1) {
    cycleId
    isFinished
    electedCouncil { id isResigned }
  }
  electedCouncils (orderBy: [createdAt_DESC] limit: 2) {
    id
    councilElections { cycleId }
  }
}
``` 

```js
{
  "data": {
    "electionRounds": [
      {
        "cycleId": 6,
        "isFinished": false, // First this should be true (since we are on the "Normal period)
        "electedCouncil": {
          "id": "00000006", // This "00000007", as "00000006" is not the latest council
          "isResigned": true
        }
      }
    ],
    "electedCouncils": [
      {
        "id": "00000007",
        "councilElections": [] // This should be [{ "cycleId": 6 }]
      },
      {
        "id": "00000006",
        "councilElections": [
          {
            "cycleId": 5 // This is correct (despite round 6 pointing at the council "00000006" ☝️)
          }
        ]
      }
    ]
  }
}
```

However the elected candidates of round 6 are the councilor of council 7.
Which confirms that `electedCouncils.councilElections` should be the electionRounds 6 for the council 7 and `electionRounds.electedCouncil` should be electedCouncils 7 for the round 6.

**Comment by bedeho** [comment]
This also came in just now, are they related? 
https://github.com/Joystream/joystream/issues/3727

**Comment by mnaamani** [comment]
> This also came in just now, are they related? #3727

Possibly: https://github.com/Joystream/joystream/issues/3727#issuecomment-1141837831

**Comment by mnaamani** [comment]
My findings
- The function in the mappings which sets the election round to isFinished = true for case when a new council is successfully elected `startNextElectionRound()` is only called when the idle period ends. https://github.com/Joystream/joystream/blob/9753012fa3e0ac06b7064564aea048fd6d7c0c26/query-node/mappings/src/council.ts#L328
- The expectation that `ElectionRound.electedCouncil` is the latest elected council is not correct. The schema documentation explains that this is the active council while the election cycle was ongoing. The newly elected council from an election round (if it is successful) is in-fact saved in `ElectionRound.nextElectedCouncil`. https://github.com/Joystream/joystream/blob/9753012fa3e0ac06b7064564aea048fd6d7c0c26/query-node/schemas/council.graphql#L250
- I can't figure out how `ElectedCouncil.councilElections` and for that matter `ElectedCouncil.councilElections` array could ever be non-empty given https://github.com/Joystream/joystream/blob/9753012fa3e0ac06b7064564aea048fd6d7c0c26/query-node/mappings/src/council.ts#L482 Are they not derived fields as I can see from the schema https://github.com/Joystream/joystream/blob/9753012fa3e0ac06b7064564aea048fd6d7c0c26/query-node/schemas/council.graphql#L213. It is also not clear to me immediately how important it is to capture this information, and I can't see it is being used in pioneer at least.


### Proposed solution
Factor out from `startNextElectionRound()` the step to conclude the an election round. This new function `concludeElectionRound()` can then be called in the `council_NewCouncilElected()` handler to update the state of the election round with isFinished = true and saving the elected council in the `.nextElectedCouncil` field. This also solves #3727
