### ISSUE TITLE
Subscan issues

### ISSUE THREAD

**Issue by mochet** [Joystream/joystream#4861]
A list of issues found with Subscan so far:

1. Circulating issuance number appears to be wrong. It appears to not be calculating the vested amount correctly.
![image](https://github.com/Joystream/joystream/assets/50830161/14b85dd7-05ea-4e71-a435-c865b7a71347)
![image](https://github.com/Joystream/joystream/assets/50830161/ecc97942-4a7c-4db5-bcc1-c819d23e1a31)

2. `Balance History` chart is not available or not populated
* https://joystream.stg.subscan.io/account/j4To6jgKfy8MgiMRDXzc15ggN8AnFAm3QJ4VXEwL3uBNMDd2s?tab=balance_history

3. Charts section includes some broken charts (https://joystream.stg.subscan.io/tools/charts)
* Daily Holder
* Daily Average Block Time
* Daily Native Token Circulating Supply
* Daily Vesting Schedule

4. Charts section includes some charts that don't apply to Joystream (https://joystream.stg.subscan.io/tools/charts)
* Treasury Available Income
* Treasury Expenses

5. Fees are in wrong units. Appear to show fees in $HAPI rather than $JOY
* https://joystream.stg.subscan.io/extrinsic/0xe8f5a2125a4cc0aba3456f597e22133e7a5830f64893a86dfbadffdc141b4e58

6. Distribution information includes `Democracy` and `Election` pallets which are not on Joystream 
![image](https://github.com/Joystream/joystream/assets/50830161/be6193eb-57af-4c67-bc12-a190e3e9cd66)

7. Inflation rate appears to be wrong--shows `4.22%` but is supposedly around `1.1%`
* Explained a bit further in this issue: https://github.com/polkadot-js/apps/issues/9860
* https://joystream.stg.subscan.io/validator

8. reward points are only tracked since era [956](https://joystream.stg.subscan.io/era?address=j4STQtK3EE3BqcNiwzW5UxN9mBiTcEQosL113JQTXzTJFU8C6&page=5) and are missing for the first 239 days.
* https://joystream.stg.subscan.io/era?address=j4STQtK3EE3BqcNiwzW5UxN9mBiTcEQosL113JQTXzTJFU8C6&page=5

9. the daily vesting release is incorrect https://joystream.stg.subscan.io/tools/charts?type=vesting_release
It states 551 kJOY release each day until 10th Dec and 306 kJOY after that.
But actually it should be around 1 MJOY each day until 10th Dec and 820 kJOY after that.

**Comment by traumschule** [comment]
reward points are only tracked since era [956](https://joystream.stg.subscan.io/era?address=j4STQtK3EE3BqcNiwzW5UxN9mBiTcEQosL113JQTXzTJFU8C6&page=5) and are missing for the first 239 days.

**Comment by mochet** [comment]
> reward points are only tracked since era [956](https://joystream.stg.subscan.io/era?address=j4STQtK3EE3BqcNiwzW5UxN9mBiTcEQosL113JQTXzTJFU8C6&page=5) and are missing for the first 239 days.

You mentioned this on Discord but when I click on that link, I can go to page 38 which shows reward points from era 85: https://joystream.stg.subscan.io/era?address=j4STQtK3EE3BqcNiwzW5UxN9mBiTcEQosL113JQTXzTJFU8C6&page=38

**Comment by traumschule** [comment]
Not sure what you are looking at. Following your link there are `-`. :)
![era85](https://github.com/Joystream/joystream/assets/31551045/7f86f0e8-0473-4303-b003-503d99982355)

**Comment by mochet** [comment]
> Not sure what you are looking at. Following your link there are `-`. :) ![era85](https://user-images.githubusercontent.com/31551045/266829576-7f86f0e8-0473-4303-b003-503d99982355.png)

oh sorry, I didn't properly read what the problem was when you shared it. Will add it to the list

**Comment by chrlschwb** [comment]
9. timestamp extrinsics do not appear.
https://joystream.stg.subscan.io/extrinsic?address=&module=timestamp&call=all&result=all&signedChecked=signed%20only&startDate=&endDate=&startBlock=&timeType=date&version=2001&endBlock=

10. the daily vesting release is incorrect. 
https://joystream.stg.subscan.io/tools/charts?type=vesting_release
It states 551 kJOY release each day until 10th Dec and 306 kJOY after that.
But actually it should be around 1 MJOY each day until 10th Dec and 820 kJOY after that.

**Comment by mochet** [comment]
> 9. timestamp extrinsics do not appear.
>    https://joystream.stg.subscan.io/extrinsic?address=&module=timestamp&call=all&result=all&signedChecked=signed%20only&startDate=&endDate=&startBlock=&timeType=date&version=2001&endBlock=

You can get timestamp extrinsics to show by changing `sign` filter from `signed only` to all: https://joystream.stg.subscan.io/extrinsic?address=&module=timestamp&call=all&result=all&signedChecked=all&startDate=&endDate=&startBlock=&timeType=date&version=2001&endBlock=

> 10. the daily vesting release is incorrect.
>     https://joystream.stg.subscan.io/tools/charts?type=vesting_release
>     It states 551 kJOY release each day until 10th Dec and 306 kJOY after that.
>     But actually it should be around 1 MJOY each day until 10th Dec and 820 kJOY after that.

will add this to the list

**Comment by carlhong** [comment]
Hi, @mochet we have fixed most issues mentioned above. 
As for issue 7, we will look into it and customize the inflation rate soon.
As for issue 8, we can only sync 120 era for now, thus no data for previous eras.
As for vesting related issue, we've re-synced corresponding data, please check again.

**Comment by yakio** [comment]
The issue 7 has been updated！

**Comment by mochet** [comment]
On the main page, when clicking `Large` transfers, no transfers will show.

**Comment by yakio** [comment]
> On the main page, when clicking `Large` transfers, no transfers will show.

Thank you for your careful testing and feedback. After our investigation, we found that this is not a bug. This list shows transfers with a real-time value of more than 100,000 USD. There is no qualifying data for now.

**Comment by bedeho** [comment]
The circulating supply is not accurate

![Screenshot 2023-09-15 at 10 13 15](https://github.com/Joystream/joystream/assets/437292/044a4e6b-afc8-47c3-8fb4-e161d42d9657)

Compare to CMC profile 

![Screenshot 2023-09-15 at 10 14 09](https://github.com/Joystream/joystream/assets/437292/69590397-efe0-4699-a26b-b8cfa5cfc346)

If you want to see how it is computed and do a comparison with what you are doing, please consult `calculateCirculatingSupply` function at this link: https://github.com/DzhideX/status-endpoint-joystream/blob/9f72f34f4cb23f5a4d3c85960a640cca3094d5a4/src/joyApi.ts#L385

**Comment by cuckooemm** [comment]
> The circulating supply is not accurate
> 
> ![Screenshot 2023-09-15 at 10 13 15](https://user-images.githubusercontent.com/437292/268219567-044a4e6b-afc8-47c3-8fb4-e161d42d9657.png)
> 
> Compare to CMC profile
> 
> ![Screenshot 2023-09-15 at 10 14 09](https://user-images.githubusercontent.com/437292/268219804-69590397-efe0-4699-a26b-b8cfa5cfc346.png)
> 
> If you want to see how it is computed and do a comparison with what you are doing, please consult `calculateCirculatingSupply` function at this link: https://github.com/DzhideX/status-endpoint-joystream/blob/9f72f34f4cb23f5a4d3c85960a640cca3094d5a4/src/joyApi.ts#L385

I have two questions
- Why `system.account` free value < miscFrozen
- Why is the lock taking the minimum value?

**Comment by bedeho** [comment]
@cuckooemm Hey, so, I think we will try to just simplify this, we have started an issue to fix this, hopefully very soon.

https://github.com/Joystream/status-endpoint-joystream/issues/45

**Comment by chrlschwb** [comment]
The API result for `https://joystream.api.subscan.io/api/scan/transfers` is incorrect. Or am I somehow doing it wrong?
Specifically, the `total` value from the results is different from the values in the UI `https://joystream.stg.subscan.io/transfer`

parameters used
```
{
    "row": 11,
    "page": 1,
    "include_total":true,
    "address":"j4WoRUngU6YgJ7ucn1MpMQCxKZsk2MsQtWJu39r3eQjNQayV4",
    "direction":"received"
}
```

API result
```
{
    "code": 0,
    "message": "Success",
    "generated_at": 1695132307,
    "data": {
        "count": 12,
        "total": {
            "JOY": {
                "sent": "0",
                "received": "110.68046444225732",
                "total": "110.68046444225732"
            }
        },
        "transfers": [...
        ]
    }
}
```

But result [here](https://joystream.stg.subscan.io/transfer?address=j4WoRUngU6YgJ7ucn1MpMQCxKZsk2MsQtWJu39r3eQjNQayV4&startDate=&endDate=&startBlock=&endBlock=&timeType=date&direction=received&result=all&minAmount=&maxAmount=&currency=usd) shows that total received is `1,739,000` JOY.

**Comment by cuckooemm** [comment]
> The API result for `https://joystream.api.subscan.io/api/scan/transfers` is incorrect. Or am I somehow doing it wrong? Specifically, the `total` value from the results is different from the values in the UI `https://joystream.stg.subscan.io/transfer`
> 
> parameters used
> 
> ```
> {
>     "row": 11,
>     "page": 1,
>     "include_total":true,
>     "address":"j4WoRUngU6YgJ7ucn1MpMQCxKZsk2MsQtWJu39r3eQjNQayV4",
>     "direction":"received"
> }
> ```
> 
> API result
> 
> ```
> {
>     "code": 0,
>     "message": "Success",
>     "generated_at": 1695132307,
>     "data": {
>         "count": 12,
>         "total": {
>             "JOY": {
>                 "sent": "0",
>                 "received": "110.68046444225732",
>                 "total": "110.68046444225732"
>             }
>         },
>         "transfers": [...
>         ]
>     }
> }
> ```
> 
> But result [here](https://joystream.stg.subscan.io/transfer?address=j4WoRUngU6YgJ7ucn1MpMQCxKZsk2MsQtWJu39r3eQjNQayV4&startDate=&endDate=&startBlock=&endBlock=&timeType=date&direction=received&result=all&minAmount=&maxAmount=&currency=usd) shows that total received is `1,739,000` JOY.

We have fixed this issue, thanks for the feedback

**Comment by bedeho** [comment]
Hey @cuckooemm, we have now cleaned up the implementation of this routine, here is the new implementation, but output is still the same as before. 

https://github.com/Joystream/status-endpoint-joystream/blob/master/src/joyApi.ts#L403 

It is now also heavily documented.

If you want to read methodology, read background issue: https://github.com/Joystream/status-endpoint-joystream/blob/master/src/joyApi.ts#L403

**Comment by bedeho** [comment]
I think one clear distinction between what we are doing and what is going on in Subscan is that tokens that are used for nomination/validation are counted as circulating by us, since they are basically available for sale on market with very short time latency, while you are counting it as not circulating.

![Screenshot 2023-09-26 at 22 35 13](https://github.com/Joystream/joystream/assets/437292/ec75d3d4-7c24-4567-9ffd-a792cf0584a2)

**Comment by bedeho** [comment]
It seems this is in conflict with what CMC & Coingecko does for example, look at Polkadot for example.

**CMC**
![Screenshot 2023-09-26 at 22 41 50](https://github.com/Joystream/joystream/assets/437292/64a8fb9c-6bcf-4f2a-9394-b8a3387e3640)

**Coingecko**
![Screenshot 2023-09-26 at 22 42 30](https://github.com/Joystream/joystream/assets/437292/f99259ed-1909-434a-9b36-c26984bcd08c)



**Subscan**

![Screenshot 2023-09-26 at 22 42 05](https://github.com/Joystream/joystream/assets/437292/800bf45a-dce3-44a4-824a-1e3ca2677456)

**Comment by yakio** [comment]
Hi @bedeho，

In general, it is true that Subscan's approach to calculating circulation differs from the methods employed by CMC/Coingecko. However, our calculation method has received recognition from Substrate ecosyste, and it is deemed to be more suitable for the Substrate ecosystem. Nevertheless, we are very open to adapting our circulation calculation method to align with the characteristics of the Joystream network, as this is indeed a crucial data point.

Regarding the slow progress, there may have been some misunderstandings. Upon seeing the issue, our team assumed that further development should proceed after the issue is merged. This misunderstanding may have caused a delay. Following the merger of this issue, we have initiated the development plan again and anticipate releasing a new test version for your team to test today. If the new version proves to be suitable for your team, we are ready to proceed with the official release and announce it to the community! I am eagerly looking forward to this moment.

**Comment by cuckooemm** [comment]
circulating supply has been updated
